### ISSUE TITLE
Add cut & fill analysis

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#44]
Add option to recreate an existing terrain in sand based on GIS information.
This could also be used to graphically visualize cut & fill differences between design iterations.

**Comment by philipbelesky** [comment]
What were you imagining the implementation here looks like? To my mind this is probably worth having a dedicated component for, and it could live downstream from the main component without a significant performance penalty. 

Essentially the inputs would be something along the lines of `MeshA` and MeshB` and the job of the component is to determine the differences between them. Those differences might drive cut/fill calculations, or a visualisation of how they differ with an eye to building a spatial overlay that directs users to shift sand in order to minimise the differences. Depending on how orthogonal those tasks are each could be a separate component.

What exactly that spatial overlay looks like would be an interesting design task — Bison provides a good precedent here although could be improved if the purpose is to guide users in sand-shifting rather than just visualising a Rhino model on its own.

**Comment by mariuszhermansdorfer** [comment]
I was primarily thinking of the sand shifting part. For more elaborate comparisons, one can always use Bison's component. Plugging it downstream of a live SandWorm component is very slow, though,

Therefore I was thinking of having this logic as part of our mesh coloring routines. Basically, another type of (exclusive) analysis, which would be selected from the right-click menu. My idea for the implementation would look like this:

1. Load an existing terrain from GIS data (or use a previously modeled mesh) 
2. Define a `samplingMask`, which is the size of  `trimmedWidth` x `trimmedHeight`
3. Scale the `samplingMask` by a scale factor corresponding to the size of the physical model in the sandbox.
4. Position the `samplingMask` at the desired location on top of the terrain mesh to be sampled
5. Sample the terrain. As a result, we would get an array of real-life elevation values for every pixel corrected for the scale of the model. Store this array and pass it to the main SandWorm component.
6. In the analysis section of the main component, compare the depth values from the Kinect with the ones stored in the `samplingMask`. If difference is negative - colorize with red color ramp. If positive - colorize with green gradient.

The above approach should result in instantaneous feedback. If we wanted, we could easily add some sort of volume estimates as well. Have two variables to track a running sum of cut and fill respectively and convert these to real-life units such as m3 or cft.

**Comment by mariuszhermansdorfer** [comment]
I'm struggling with finding a good way of passing data of different types between the `SandWormOptions` and `SandWorm` components. So far it is an [array of double](https://github.com/mariuszhermansdorfer/SandWorm/blob/7d31f2e8556d574f131acfd49b4ebffebd091adc/SandWorm/SandWormSetup.cs#L19) but this is somewhat limiting. 

How would you approach passing the above described `samplingMask` along all the other variables? I can't see anything useful in the [official methods](https://developer.rhino3d.com/api/grasshopper/html/Methods_T_Grasshopper_Kernel_GH_Component_GH_InputParamManager.htm).

**Comment by philipbelesky** [comment]
I would just create a class/struct that contains the key/value pairs and pass an object with all the different values. If you use `AddGenericParameter` you can send/receive arbitrary objects; for instance the (very underdeveloped) Groundhog planting components both [send](https://github.com/philipbelesky/groundhog/blob/develop/plugin/Plants/PShowerComponent.cs#L34) and [receive](https://github.com/philipbelesky/groundhog/blob/develop/plugin/Plants/PGenericComponent.cs#L29) a `PlantSpecies` class [that inherits from `GH_Param<IGH_Goo>`](https://github.com/philipbelesky/groundhog/blob/develop/plugin/Plants/Plants.cs#L251).

**Comment by philipbelesky** [comment]
And yes, adding the delta by colorizing the mesh would be a great and easily-integrated solution. There might be some value in additional information atop the color mesh (e.g. the exact height differences in text?) but that could be dealt with as a geometry-outputting analysis type if it ends up being useful.

**Comment by mariuszhermansdorfer** [comment]
First sketches started in [this branch](https://github.com/mariuszhermansdorfer/SandWorm/blob/feature/cutfill/SandWorm/CutFill.cs).

Users can define a rectangle of any size and orient it at will over an existing mesh. The grid of sample points is being created automatically based on the data from `SandWormSetup` and an additional `ScaleFactor` slider. 
Still need to add the actual sampling logic, but wanted to share the progress.
![image](https://user-images.githubusercontent.com/49192999/65839079-2ca99480-e30a-11e9-9cf4-566be0da41c0.png)

![image](https://user-images.githubusercontent.com/49192999/65839084-3b904700-e30a-11e9-86bd-eeae4581f377.png)

**Comment by mariuszhermansdorfer** [comment]
First prototype ready. Initial calibration (#40) is almost ready as well. Will tweak a few things and merge to master soon.
Quick demo [video here](https://youtu.be/hjYE-N-2Eac)

![image](https://user-images.githubusercontent.com/49192999/66954785-5cbe9a80-f061-11e9-96b5-cfea132b5e82.png)

**Comment by philipbelesky** [comment]
That looks great! Manipulating the sand so that the mesh shifts from green/red to white seems like a very zen game.

**Comment by philipbelesky** [comment]
It took me a while to understand how to get this working as I had initially misinterpreted the image above and the role of the rectangle was not clear. I thought it was a cropping tool (which it sort of is) but didn't realise that it assumes that the cropped mesh area is larger than the Kinect's mesh. Thus when I was using it (on a baked out copy of a Kinect capture) there was always a mismatch between the quantity of `MeshElevationPoints` and `projectedPoints` that caused an index overflow. If I changed lines 141 and 150 of `MeshCompareComponent` to iterate over `projectedPoints.Length` that fixes in Index error, but means that the the visualisation only extends up a couple of rows.
 
It seems like the broader issue is that the results of the projection assumes that all of the points 'hit' the mesh and that the quantity of points used in the projection matches that of the mesh. 

In writing this out I figured out that the purpose of the rectangle is always to 'crop' down a larger mesh (i.e. a large site area) to the approximate area of the sandbox. But, I think this use is not intuitive and the component will need to (perhaps after landing the PR) to do work to check for valid inputs and help guide users in its correct use. Alternately the role of the rectangle could expand to become more flexible and account for more use cases. That could include:

- Allowing the rectangle to crop a smaller area. For instance, if you are compared the current mesh to a previous Kinect capture, you might want to only visualise cut/fill within a particular subset rather than across the whole terrain. 
  - This would also mean that the cut/fill visualisation would not need to be mutually exclusive with other options (although it would take priority).
  - This would also mean the rectangle could be any arbitrary closed curve. In which case the point grid would need to be culled to its bounds, but that would be pretty easy to manage. 
- Does the rectangle need to be a required parameter? A common use case might be comparing the current mesh to a previously-baked out mesh; in which case we could just use bounding boxes to determine the point grid? This could also provide an easier setup process as it would immediately show a cut/fill visualisation, and the warping effects would be suggest to users that the rectangle should be used.

Some other thoughts on the Cut/Fill component also:

- The output of MeshCompareOptions is not intuitively related to Elevation Points; I wouldn't have know to connect them without your picture
- Is `Scale Factor` the right label? It seems more like its related to the resolution of the point grid; i.e. it determines the fidelity of the output rather than its size
